# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Delving
email: info@delving.eu
description: > # this means to ignore newlines until "baseurl:"
  Delving provides open-source solutions for the Cultural Heritage sector
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://delving.github.io" # the base hostname & protocol for your site
twitter_username: delvingEU
github_username:  delving
timezone: Europe/Amsterdam

# Build settings
markdown: kramdown
